export const TEXT = {
  connections: 'Företagskopplingar',
  integrations: 'Integrationer',
  users: 'Användare',
  cancelText: 'Avbryt',
  saveText: 'Spara',
  start: 'Start',
  user: {
    name: 'Namn',
    socialSecurityNumber: 'Personnummer: ',
    dialog: {
      editTitle: 'Ändra användaruppgifter',
      editConfirmButtonText: 'Uppdatera',
    },
  },
  systemInfo: {
    title: 'Meddelanden',
    date: 'Datum',
    login: 'Logga in',
    start: 'Startsidan',
    bank: 'Bank & Betalning',
    warning: 'Varning',
    info: 'Info',
    beta: 'Beta',
    dialog: {
      deleteTitle: 'Vill Du ta bort infoposten?',
      editTitle: 'Ändra infomeddelande',
      createTitle: 'Lägg till infomeddelande',
      deleteConfirmButtonText: 'Ja, ta bort',
      editConfirmButtonText: 'Uppdatera',
      createConfirmButtonText: 'Lägg till',
      cancelButtonText: 'Avbryt',
    },
    list: {
      level: 'Typ:',
      label: 'Placering:',
      active: 'Aktiv:',
      message: 'Meddelande:',
      icon: 'Ikon:',
      expireAt: 'Giltig till:',
      createdAt: 'Skapad:',
      id: 'Id:',
      newButtonText: 'Skapa ny',
    },
  },
  connection: {
    title: 'Företagskoppling',
  },
  company: {
    title: 'Företag',
    emailPortalAddress: 'Epost-Portal Adress',
    publicKey: 'Företagsnyckel',
    payingCustomerNumber: 'Betalandekundnummer',
    allocatingCustomerNumber: 'Allokerandekundnummer',
    firmCustomerNumber: 'Byråkundnummer',
    searchText: 'Sök på',
    id: 'Id',
    connectedToBlApp: 'Ansluten till Bl App',
    orgNumber: 'Organisationsnummer',
    databaseName: 'Databasnamn',
    userId: 'Användarnamn',
    blaPassword: 'BLA Lösenord',
    email: 'Epost',
    hostId: 'Molnserver',
    dropdownTitle: 'Ingen företagskoppling vald - Välj i listan för att visa detaljer',
  },
  bank: {
    name: 'Bankstatus',
    bank: 'Bank',
    iban: 'IBAN',
    active: 'Aktiv',
    valid: 'Giltig',
    userKey: 'Användarnyckel',
    assignmentId: 'Uppdrags id',
    lastTransfer: 'Senaste transaktionen',
    timeStamp: 'Datum',
    status: 'Status',
    error: 'Fel',
    message: 'Meddelande',
    path: 'Ursprung',
    seb: 'SEB',
    hb: 'Handelsbanken',
  },
  integration: {
    integrations: 'Integrationer',
    integrator: 'Integratör',
    active: 'Aktiv',
    scope: 'Åtkomst',
    createTime: 'Skapad',
    description: 'Här ser du kopplade integrationer',
  },
  skv: {
    name: 'Skatteverket',
    skvNumber: 'Organisationsnummer',
    skvInitiator: 'Initierare',
    description: 'Här ser du om det finns en koppling',
  },
  subscription: {
    title: 'Nuvarande abonnemang',
    basePrice: 'Paket baspris',
    extraUser: 'Extraanvändare',
    blAllInclusive: 'Helhetslösningsanvändare',
    modulePrice: 'Modulpris',
    pricePerUser: 'Pris per användare',
    user: 'anv',
    userIncluded: 'anv ingår',
    monthlyCost: 'Total månadskostnad: ',
    integrationDiscount: 'Paketrabatt Tolkning + e-postportal',
  },
};
