import { Menu } from '../models/menu';
import { Roles } from '../enums/roles';
import { TEXT } from '@shared/text.constants';

export const MENU_ITEMS: Menu[] = [
  {
    id: 0,
    property: '',
    displayName: TEXT.start,
    path: '/',
    icon: 'fa-home',
    badge: null,
    roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
    children: [],
  },
  {
    id: 1,
    property: 'user',
    displayName: TEXT.users,
    path: '/users',
    icon: 'fa-user',
    badge: null,
    roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
    children: [
      {
        id: 1,
        property: 'user',
        displayName: '{id}',
        path: '/users/:id',
        icon: 'fa-user',
        badge: null,
        roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
        children: [],
      },
    ],
  },
  {
    id: 2,
    property: 'company',
    displayName: TEXT.company.title,
    path: '/companies',
    icon: 'fa-building',
    badge: null,
    roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
    children: [
      {
        id: 1,
        property: 'company',
        displayName: '{id}',
        path: '/companies/:id',
        icon: 'fa-building',
        badge: null,
        roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
        children: [],
      },
    ],
  },
  {
    id: 3,
    property: 'connections',
    displayName: TEXT.connections,
    path: '/connections',
    icon: 'fa-plug',
    badge: null,
    roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
    children: [],
  },
  {
    id: 4,
    property: 'systemInfo',
    displayName: TEXT.systemInfo.title,
    path: '/system-info',
    icon: 'fa-info',
    badge: null,
    roleAccess: [Roles[Roles.Admin], Roles[Roles.Dev],Roles[Roles.User]],
    children: [],
  },
  // {
  //   id: 4,
  //   property: 'property',
  //   displayName: 'Property',
  //   path: '/properties',
  //   icon: 'fa-project-diagram',
  //   badge: null,
  //   roleAccess: [Roles[Roles.Admin]],
  //   children: [],
  // },
  // {
  //   id: 5,
  //   property: 'integrations',
  //   displayName: TEXT.integrations,
  //   path: '/integrations',
  //   icon: 'fa-puzzle-piece',
  //   badge: null,
  //   roleAccess: [Roles[Roles.Admin], Roles[Roles.User], Roles[Roles.Dev]],
  //   children: [],
  // },
];
